-- 074_admin_audit_log.sql
--
-- Admin action audit trail (Phase 1, Slice 1.3c of the admin panel).
-- (Numbered 074 because the parallel ride-board sprint took 073.)
--
-- Every write the admin panel performs against user data writes ONE
-- row here so we have a forensic record of "who did what to whom
-- and when." Reads do NOT log (the dashboard / search / overview tabs
-- are read-only; logging every page view would 100x the row count
-- with low signal).
--
-- Schema choices:
--   - `id`            : surrogate PK, uuid v4 generated by gen_random_uuid
--   - `admin_id`      : the admin user (auth.uid from the JWT). NOT NULL
--                       — every audit row must attribute to a real admin
--   - `target_user_id`: the user the action was performed against. NULL
--                       allowed for actions that don't target a specific
--                       user (e.g. broadcast campaigns in Slice 1.4).
--   - `action`        : short snake_case token (`send_push`,
--                       `grant_wallet_credit`, etc.) — text not an
--                       enum so we can add new actions without a
--                       migration each time.
--   - `payload`       : jsonb blob with everything the action needed.
--                       Format is action-specific:
--                         send_push       → { title, body }
--                         grant_credit    → { amount_cents, reason }
--                         override_onb    → { from, to }
--                         (etc.)
--                       Include the REASON the admin gave so the row
--                       reads end-to-end without joins.
--   - `created_at`    : tz-aware. Indexed.
--
-- RLS:
--   - All access is server-side via the service role; we don't grant
--     SELECT to authenticated users. (Admins read this via the admin
--     panel which uses supabaseAdmin, bypassing RLS.)
--   - ENABLE RLS with no SELECT policy so a regular user with a
--     stolen anon key can't query the table.
--
-- Indexes:
--   - (target_user_id, created_at desc) drives the per-user Admin
--     Actions audit list on user detail pages (newest-first).
--   - (admin_id, created_at desc) drives "who's been most active"
--     queries we'll surface in a later slice.
--   - (created_at desc) for the global audit log nav tab (Slice 1.8).

CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id        UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  target_user_id  UUID REFERENCES public.users(id) ON DELETE SET NULL,
  action          TEXT NOT NULL,
  payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.admin_audit_log IS
  'Forensic record of every write the admin panel performs. One row per action. See migration 074 + ADMIN_PLAN.md.';

ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

-- No SELECT / INSERT / UPDATE / DELETE policies — service role only.

CREATE INDEX IF NOT EXISTS idx_admin_audit_target_created
  ON public.admin_audit_log (target_user_id, created_at DESC)
  WHERE target_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_admin_audit_admin_created
  ON public.admin_audit_log (admin_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_created
  ON public.admin_audit_log (created_at DESC);
